name: flutter_test_example
description: Flutter mobile app test example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  uuid: ^3.0.7
  localstorage: ^4.0.0+1
  intl: ^0.18.0
  flutter_gherkin: ^2.0.0
  glob: ^2.1.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
